name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ python3 make libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/local/lib

      - name: Build project and tests
        run: |
          make
          make test

      - name: Run unit tests
        run: |
          if [ -f "./unit_tests" ]; then
            ./unit_tests
          else
            echo "Error: unit_tests executable not found!"
            ls -la
            exit 1
          fi

      - name: Run python tests
        run: python3 tests.py