name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y g++ make libgtest-dev

      - name: Copy GoogleTest libraries to /usr/local/lib
        run: |
          sudo mkdir -p /usr/local/lib
          sudo cp /usr/lib/x86_64-linux-gnu/libgtest.a /usr/local/lib/
          sudo cp /usr/lib/x86_64-linux-gnu/libgtest_main.a /usr/local/lib/

      - name: Build project and tests
        run: |
          make
          make test


      - name: Run unit tests
        run: |
          if [ -f "./unit_tests" ]; then
            ./unit_tests
          else
            echo "Error: unit_tests executable not found!"
            ls -la
            exit 1
          fi