name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ python3 make cmake libgtest-dev libgtest
          sudo apt-get install -y googletest

      - name: Build GTest manually
        run: |
          mkdir -p ~/gtest-build
          cd ~/gtest-build
          cmake /usr/src/googletest
          make
          sudo cp lib/*.a /usr/local/lib

      - name: Build and test project
        run: |
          make
          make test
          
          
          if [ ! -f "./unit_tests" ]; then
            echo "=== Error: unit_tests not found! ==="
            echo "Содержимое папки:"
            ls -la
            echo "Попытка найти исполняемые файлы:"
            find . -type f -executable
            exit 1
          fi
          
          ./unit_tests

      - name: Run python tests
        run: python3 tests.py